version: '2'
services:
        mongodb:
                image: 'mongo'
                ports:
                        - 27017

        redis:
                image: 'redis'
                ports:
                        - 6379

        whomi:
                image: '$INSERT_USERNAME/whomi'
                ports:
                        - 1337
